import type { MagazineCategory } from '@/types/magazine'

export const MAGAZINE_CATEGORIES: MagazineCategory[] = [
  {
    id: 'produce',
    name: { en: 'Fresh Produce', ar: 'المنتجات الطازجة' },
    icon: '🥬',
    color: '#5a7c5a',
    offers: [
      {
        id: 'prod-1',
        item: { en: 'Organic Apples', ar: 'تفاح عضوي' },
        description: { en: '1kg bag, Premium selection', ar: 'كيس 1 كجم، اختيار مميز' },
        originalPrice: '15.99',
        discountedPrice: '9.99',
        discount: '38%',
        category: 'produce',
        badge: 'hot',
      },
      {
        id: 'prod-2',
        item: { en: 'Fresh Tomatoes', ar: 'طماطم طازجة' },
        description: { en: 'Local farm, per kg', ar: 'من المزرعة المحلية، للكيلو' },
        originalPrice: '8.99',
        discountedPrice: '5.99',
        discount: '33%',
        category: 'produce',
      },
      {
        id: 'prod-3',
        item: { en: 'Avocado Pack', ar: 'علبة أفوكادو' },
        description: { en: '4 pieces, Ready to eat', ar: '4 حبات، جاهز للأكل' },
        originalPrice: '24.99',
        discountedPrice: '17.99',
        discount: '28%',
        category: 'produce',
        badge: 'bestseller',
      },
      {
        id: 'prod-4',
        item: { en: 'Organic Mangoes', ar: 'مانجو عضوي' },
        description: { en: 'Premium quality, 1kg', ar: 'جودة ممتازة، 1 كجم' },
        originalPrice: '32.99',
        discountedPrice: '24.99',
        discount: '24%',
        category: 'produce',
        outOfStock: true,
      },
    ],
  },
  {
    id: 'dairy',
    name: { en: 'Dairy & Eggs', ar: 'الألبان والبيض' },
    icon: '🥛',
    color: '#7a9bb5',
    offers: [
      {
        id: 'dairy-1',
        item: { en: 'Fresh Milk 2L', ar: 'حليب طازج 2 لتر' },
        description: { en: 'Full fat, Local dairy', ar: 'كامل الدسم، ألبان محلية' },
        originalPrice: '12.99',
        discountedPrice: '8.99',
        discount: '31%',
        category: 'dairy',
        badge: 'hot',
      },
      {
        id: 'dairy-2',
        item: { en: 'Greek Yogurt 500g', ar: 'زبادي يوناني 500 جم' },
        description: { en: 'Natural, High protein', ar: 'طبيعي، عالي البروتين' },
        originalPrice: '18.99',
        discountedPrice: '13.99',
        discount: '26%',
        category: 'dairy',
      },
      {
        id: 'dairy-3',
        item: { en: 'Eggs (30 pack)', ar: 'بيض (30 حبة)' },
        description: { en: 'Free range, Large', ar: 'حر، حجم كبير' },
        originalPrice: '29.99',
        discountedPrice: '22.99',
        discount: '23%',
        category: 'dairy',
        badge: 'new',
      },
      {
        id: 'dairy-4',
        item: { en: 'Imported Cheese Selection', ar: 'تشكيلة أجبان مستوردة' },
        description: { en: 'Premium European varieties', ar: 'أصناف أوروبية ممتازة' },
        originalPrice: '89.99',
        discountedPrice: '69.99',
        discount: '22%',
        category: 'dairy',
        outOfStock: true,
      },
    ],
  },
  {
    id: 'meat',
    name: { en: 'Meat & Poultry', ar: 'اللحوم والدواجن' },
    icon: '🥩',
    color: '#8b6b61',
    offers: [
      {
        id: 'meat-1',
        item: { en: 'Chicken Breast 1kg', ar: 'صدور دجاج 1 كجم' },
        description: { en: 'Boneless, Fresh', ar: 'بدون عظم، طازج' },
        originalPrice: '35.99',
        discountedPrice: '24.99',
        discount: '31%',
        category: 'meat',
        badge: 'hot',
      },
      {
        id: 'meat-2',
        item: { en: 'Beef Mince 500g', ar: 'لحم بقري مفروم 500 جم' },
        description: { en: 'Lean, Premium quality', ar: 'قليل الدهون، جودة ممتازة' },
        originalPrice: '28.99',
        discountedPrice: '19.99',
        discount: '31%',
        category: 'meat',
        badge: 'bestseller',
      },
      {
        id: 'meat-3',
        item: { en: 'Wagyu Beef Steak', ar: 'ستيك لحم واغيو' },
        description: { en: 'A5 Grade, 300g', ar: 'درجة A5، 300 جم' },
        originalPrice: '199.99',
        discountedPrice: '159.99',
        discount: '20%',
        category: 'meat',
        outOfStock: true,
      },
    ],
  },
  {
    id: 'bakery',
    name: { en: 'Bakery', ar: 'المخبوزات' },
    icon: '🥐',
    color: '#c4a574',
    offers: [
      {
        id: 'bakery-1',
        item: { en: 'Sourdough Bread', ar: 'خبز العجين المخمر' },
        description: { en: 'Fresh baked daily', ar: 'يخبز طازجاً يومياً' },
        originalPrice: '14.99',
        discountedPrice: '9.99',
        discount: '33%',
        category: 'bakery',
        badge: 'new',
      },
      {
        id: 'bakery-2',
        item: { en: 'Croissants (6 pack)', ar: 'كرواسون (6 حبات)' },
        description: { en: 'Butter, French style', ar: 'بالزبدة، على الطريقة الفرنسية' },
        originalPrice: '22.99',
        discountedPrice: '15.99',
        discount: '30%',
        category: 'bakery',
      },
      {
        id: 'bakery-3',
        item: { en: 'Gluten-Free Bread', ar: 'خبز خالي من الغلوتين' },
        description: { en: 'Artisan recipe, 500g', ar: 'وصفة حرفية، 500 جم' },
        originalPrice: '18.99',
        discountedPrice: '14.99',
        discount: '21%',
        category: 'bakery',
        outOfStock: true,
      },
    ],
  },
  {
    id: 'beverages',
    name: { en: 'Beverages', ar: 'المشروبات' },
    icon: '🥤',
    color: '#7a8b7a',
    offers: [
      {
        id: 'bev-1',
        item: { en: 'Orange Juice 1.5L', ar: 'عصير برتقال 1.5 لتر' },
        description: { en: '100% Natural, No sugar', ar: '100% طبيعي، بدون سكر' },
        originalPrice: '16.99',
        discountedPrice: '11.99',
        discount: '29%',
        category: 'beverages',
        badge: 'bestseller',
      },
      {
        id: 'bev-2',
        item: { en: 'Sparkling Water 12pk', ar: 'مياه فوارة 12 عبوة' },
        description: { en: 'Premium, Flavored', ar: 'ممتاز، بنكهات' },
        originalPrice: '24.99',
        discountedPrice: '17.99',
        discount: '28%',
        category: 'beverages',
      },
      {
        id: 'bev-3',
        item: { en: 'Coconut Water 6pk', ar: 'ماء جوز الهند 6 عبوات' },
        description: { en: 'Organic, Fresh pressed', ar: 'عضوي، معصور طازج' },
        originalPrice: '34.99',
        discountedPrice: '27.99',
        discount: '20%',
        category: 'beverages',
        outOfStock: true,
      },
    ],
  },
]

// Calculate the next Sunday for "valid until" date
export function getValidUntilDate(): string {
  const today = new Date()
  const daysUntilSunday = (7 - today.getDay()) % 7 || 7
  const nextSunday = new Date(today)
  nextSunday.setDate(today.getDate() + daysUntilSunday)
  return nextSunday.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })
}
